import Head from 'next/head'
import Timetable from '../components/Timetable'

export default function Home() {
  const schedules = [
    [
      { name: 'Foo', start: 0, end: 3 },
    ],
  ];

  return (
    <div className="container mx-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className="py-20">
        <Timetable dateStartAt={new Date('2021-07-12')} schedules={schedules} />
      </main>
    </div>
  )
}
